### ISSUE TITLE
Incorrectly reuses json environment variable as javascript variable

### ISSUE THREAD

**Issue by lwouis** [loadimpact/postman-to-k6#10]
You can pick environment variable names in your JSON file which are illegal javascript variable name. Typical case would be using a dash.

Example:
- environment variable `"key": "client-id"` will become `let client-id = "YOUR_VALUE";`
- reference to environment variable `{{client-id}}` will become reference to `client-id`

A very simple fix would be to assign all the variable to an object like `env` so we can reuse the illegal names with `env['client-id']`. I think it's also nicer anyways because one can then import an `env` from another file and reuse environments this way.

**Comment by robingustafsson** [comment]
@lwouis We released a new version of the converter today that has broader and better support for the Postman feature set, including support for environment variables with env var names containing illegal JS variable name characters. If you export your environment variables from Postman (to say `MyEnvVars.postman_environment.json`) you can now convert a collection like this:

```shell
postman-to-k6 MyCollection.postman_collection.json -o MyTest.js -e MyEnvVars.postman_environment.json
```

Hope that helps. Closing this issue (and the PR). Please re-open if you think we've missed something.
