### ISSUE TITLE
Failed to convert POST request with no post data to proper k6 request

### ISSUE THREAD

**Issue by mohanbmahajan** [loadimpact/postman-to-k6#2]
From the postman  POSTrequest with no post data it got converted to following,

http.post(url+"?grant_type=password&username=xyz&password=xyz", { headers: headers });

I have to edit this and also pass body to make it work. Following is the working request,

http.post(url+"?grant_type=password&username=xyz&password=xyz", null, { headers: headers });

**Comment by ppcano** [comment]
@mohanbmahajan Thanks for reporting.

Released `v0.0.2` with a fix. Please, let us know if the problem persists.
