### ISSUE TITLE
Request decomposition [bounty: $200]

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/postman-to-k6#24]
Add a CLI option to output each request in a collection to a separate JS file. Groups should be respected and create necessary folder tree in output directory.

**Comment by robingustafsson** [comment]
https://www.bountysource.com/issues/72323805-request-decomposition-bounty-200

**Comment by bookmoons** [comment]
[`bookmoons/request-decomp`](https://github.com/bookmoons/postman-to-k6/tree/bookmoons/request-decomp) has something to submit for this, but it touches the same files as an open PR. Will hold off until that's done so I can handle conflicts.

**Comment by bookmoons** [comment]
Submitted what I had for this, but I hadn't thought of the bit about the directory structure. Is that important? I can revisit.

**Comment by bookmoons** [comment]
Submitted a version of this with directories in #31. The converted files look pretty sleek.
