### ISSUE TITLE
Add support for variables in protocol

### ISSUE THREAD

**Issue by mintbridge** [loadimpact/postman-to-k6#27]
Hi, 

Firstly thank you for creating this its awesome.

We use a variable in the protocol part of the url (e.g. `{{protocol}}://hostname.{{env}}.domain.tld/api/v5/ping` so that we can use env vars to can between http and https for local and server environments. When i convert the the collection the resulting urls come out with the extra protocol, e.g `address: "http://{{protocol}}://hostname.{{env}}.domain.tld/api/v5/ping",` which i think is caused by https://github.com/loadimpact/postman-to-k6/blob/master/lib/generate/Request.js#L40

Not sure what the best way round this is?

**Comment by robingustafsson** [comment]
Happy you like the tool @mintbridge :)

I think the solution here would be to make sure the variables in the URL are resolved/evaluated before we parse and do modifications like prepending "http" at JS generation time. So moving the code in https://github.com/loadimpact/postman-to-k6/blob/master/lib/generate/Request.js#L40 to after this line https://github.com/loadimpact/postman-to-k6/blob/master/lib/shim/core.js#L933.

@bookmoons Thoughts? Also, I think we should default to "https" unless there's a convention in Postman to default to "http"?

**Comment by mintbridge** [comment]
yeah sounds good, i just wasnt sure where to do it, happy to put up a PR if someone can point me in the right direction

**Comment by bookmoons** [comment]
Shoot, did intend for this to work.

If you just add a check for a variable at the start to that line you found, I think it should work. Something like:

```js
if (!feature.address.protocol() && !/^{{/.test(feature.address.toString())) {
  feature.address.protocol('http')
}
```

It deserves a test in `test/int/var.js`. If you can make an export with a test case and put it in eg `test/material/2.1/var-start.json`, then you can follow the pattern of the other tests.

**Comment by bookmoons** [comment]
> I think the solution here would be to make sure the variables in the URL are resolved/evaluated before we parse and do modifications like prepending "http" at JS generation time. So moving the code in https://github.com/loadimpact/postman-to-k6/blob/master/lib/generate/Request.js#L40 to after this line https://github.com/loadimpact/postman-to-k6/blob/master/lib/shim/core.js#L933.

Scratch what I said, Robin has the more robust approach. Let me look again and I'll write up some guidance.

**Comment by bookmoons** [comment]
It seems like that is the way to do it, parse at runtime after variable replacement. It requires the URI library. The program is trying hard to minimize memory usage, so there's a special way to handle it. I will try to summarize.

Suggesting here to make it conditional, to keep the URI library out of it for the simple case.

* In the shim `postman[Extend]` offers a place to drop external libraries. `URI` can be defaulted `null` there. Then eg `shim/uri.js` can be defined which will load the library and drop it in `Extend`. You can look at eg `shim/expect.js` for an example. The `urijs` module is already bundled for another purpose to it can be imported with `import URI from ../urijs.js`.
* At convert time detect the variable-at-start case and signal URI should be loaded, with `result.effectImports.add('./libs/shim/uri.js')`. You'll have to pass `result` down to `address()`. https://github.com/loadimpact/postman-to-k6/blob/db01547024a66dfe1f70eab7672c79cb9a14e866/lib/generate/Request.js#L37
* In the place Robin pointed out parsing and protocol defaulting can be done at runtime. Test the address and only run if a variable is at the start. https://github.com/loadimpact/postman-to-k6/blob/db01547024a66dfe1f70eab7672c79cb9a14e866/lib/shim/core.js#L933

A trace shows the Postman app does no TLS connection if the protocol is left out. So I think the default should be `http`.

**Comment by mintbridge** [comment]
sorry it took so long, i didnt need to use the shim in the end: https://github.com/loadimpact/postman-to-k6/pull/30

**Comment by mintbridge** [comment]
@bookmoons any thoughts on the PR?

**Comment by bookmoons** [comment]
Thanks for the submission @mintbridge. Left a comment there.

It's unfortunate this is kind of involved, because of the bundling thing. I think I saw the engine is planning to add the new `URL` API (@robingustafsson ?). Possibly it's worth waiting for that, because it would make this easier. The bundling piece would disappear.
