### ISSUE TITLE
Postman variables in body won’t get replaced

### ISSUE THREAD

**Issue by cpcalderon** [loadimpact/postman-to-k6#32]
Issue #12 seems isn't completely solved. Opened forum question here:
https://community.k6.io/t/postman-variables-in-body-wont-get-replaced/113

Seems the answer from tamitakamiya fixes the issue, at least for me.

```I had the same issue and it was resolved by replacing the line 935 of libs/shim/core.js, ie.
config.data = data
to
config.data = evaluate(data)

**Comment by bookmoons** [comment]
[`bookmoons/body-var`](https://github.com/bookmoons/postman-to-k6/tree/bookmoons/body-var) has a fix for this to submit when open PRs are done.

Thanks for the report @cpcalderon.
