### ISSUE TITLE
Support New Body Mode GraphQL for Postman Collections

### ISSUE THREAD

**Issue by dmhalejr** [loadimpact/postman-to-k6#36]
Using Postman Version 7.2.2 with the new `graphql` body mode and ran into:
```
Error: Unrecognized body mode: graphql
``` 

Looks like `postman-collection` version 3.4.7 supports the new `graphql` body mode. 

Would love for it to be supported here! Let me know if I can assist with a PR.

**Comment by bookmoons** [comment]
Thanks for this. Really interesting new feature. Going to have a look when I can.

**Comment by johnhiggs** [comment]
any chance there will be support for graphQL in the future?
