### ISSUE TITLE
Getting a warning

### ISSUE THREAD

**Issue by vaibhavpacharya** [loadimpact/postman-to-k6#39]
Getting this error / warning. Is there any way to bypass this warning like "node --no-warnings".

`(node:50912) ExperimentalWarning: The fs.promises API is experimental
`

**Comment by simskij** [comment]
Thank you for submitting a question! 🙏🏼

This should likely solve your issue:

### If you have postman-to-k6 installed globally
```shell
$ node --no-warnings $(which postman-to-k6)
```

### If you have postman-to-k6 installed in your current repo
```shell
$ node --no-warnings ./node_modules/.bin/postman-to-k6
```

Please try it out and let me know whether it solves your issue!

**Comment by simskij** [comment]
Closing due to lack of response.
