### ISSUE TITLE
'k6' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by lobmails** [loadimpact/postman-to-k6#4]
Hi,

I followed the steps to configure k6 on Windows 10 and getting the error: 'k6' is not recognized as an internal or external command.

I have installed k6.exe (x64) and executing the steps in the mentioned order

git clone git@github.com:loadimpact/postman-to-k6.git
cd postman-to-k6
npm install

#On windows
node bin/postman-to-k6.js examples/postman/v2/echo.json

k6 run k6-script.js

Getting error at the last command: k6 run k6-script.js

**Comment by ppcano** [comment]
@lobmails Sorry for the confusion, but the instructions expect `k6` to be installed on your machine.

https://k6.readme.io/docs/installation

Please, let me know if the installation solves the issue.

**Comment by rubal-jain** [comment]
@ppcano the k6 installation is giving error:
"Error: cannot load such file -- language/node"

any idea what this is about?

**Comment by ppcano** [comment]
@rubal-jain 

If the problem is the `k6` installation, I recommend you:

-  ask for help in the [Slack Channel](https://k6.io/slack/)
-  if it is a bug; open an issue in the [k6 project](https://github.com/loadimpact/k6) with a detailed description of your environment and the steps to reproduce it
