### ISSUE TITLE
TypeError: Object has no member ‘replace’

### ISSUE THREAD

**Issue by marcelo-dalmeida** [loadimpact/postman-to-k6#42]
As mentioned in:
https://community.k6.io/t/typeerror-object-has-no-member-replace/253

"Hi

I’ve just converted a postman collection through postman-to-k6 tool.

I’m having the current problem when executing the script and it seems to be connected to http.file part

I’m out of clues about what is happening here

code:
```
export default function() {
		
  postman[Request]({
    name: "/recommendation (file upload)",
    id: "72996999-1924-45d4-8b65-1e1867785397",
    method: "POST",
    address: "{{recommendation-url}}/recommendation?start=1&limit=10",
    data: { user_id: "5", file: http.file(document_file) },
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      var jsonData = JSON.parse(responseBody);
      postman.setEnvironmentVariable(
        "recommendation_request.id",
        jsonData.recommendation_request.id
      );
    }
  });
```
Error raised while running the script:
```
ERRO[0005] TypeError: Object has no member 'replace'
        at makeRequestConfig (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:996:205(117))
        at executeRequest (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:960:35(78))
        at executeRequest (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:956:234(53))
        at file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:307:46(35)
        at file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/recommendation-k6-script.js:37:19(31)
    done [==========================================================] 1 / 1
```
Thank you in advance"

P.S. It is uploading a word document (binary)

**Comment by Lex-talionis** [comment]
i'm having the same problem, its this makeRequestConfig() in core.js. i could hack it about to work but there has surely got to be a fix to this?

**Comment by bookmoons** [comment]
Hi guys. Thanks for the report. I'll be looking into this soon.

**Comment by bookmoons** [comment]
Does someone have an example collection they can post? My tests are not reproducing.

**Comment by bookmoons** [comment]
Hi guys. Would really like to fix this bug but so far I haven't found an input that causes it. If someone could send a Postman collection that causes it, that would help a lot. I'd be able to find what's happening and publish a fix. @marcelo-dalmeida @Lex-talionis

**Comment by marcelo-dalmeida** [comment]
Hi @bookmoons 

Sorry for the delay. 

It is basically a ms/word file upload (binary file upload handling)

Here is the collection I was using it:
[recommendation.postman_collection.zip](https://github.com/loadimpact/postman-to-k6/files/3745258/recommendation.postman_collection.zip)

**Comment by bookmoons** [comment]
Thanks a lot @marcelo-dalmeida. Will investigate.

**Comment by bookmoons** [comment]
This is the conversion I see. The `file` part of the body is an empty string. Still not quite right but tt's different than the report where it's an `http.file()` call.

Is this also what you see? Is it possible you were adding that `http.file()` call manually ?

```js
    data: { user_id: "5", file: "" },
```

```js
  postman[Request]({
    name: "/recommendation (file upload)",
    id: "05cc76cd-214f-46b7-a251-5219b509eab1",
    method: "POST",
    address: "{{recommendation-url}}/recommendation?start=1&limit=10",
    data: { user_id: "5", file: "" },
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      var recommendation_url = postman.getEnvironmentVariable(
        "recommendation-url"
      );

      if (
        recommendation_url.startsWith("{{") &&
        recommendation_url.endsWith("}}")
      ) {
        var url_variable = recommendation_url;

        url_variable = url_variable.replace("{{", "");
        url_variable = url_variable.replace("}}", "");

        new_recommendation_url = postman.getEnvironmentVariable(url_variable);

        postman.setEnvironmentVariable(
          "recommendation-url",
          new_recommendation_url
        );
      }

      var jsonData = JSON.parse(responseBody);
      postman.setEnvironmentVariable(
        "recommendation_request.id",
        jsonData.recommendation_request.id
      );
    }
  });
```

**Comment by marcelo-dalmeida** [comment]
I'm not with a computer right now to further check if I got the same and exactly what I did after, but you are right.

I remember now that it didn't work by purely converting it, so I tried to fill the blanks manually. And then I found this error.

So it is probably two separate bugs.

**Comment by bookmoons** [comment]
OK thanks a lot for your help. Going to build a fix.
