### ISSUE TITLE
When trying to run the *.js file using the k6 command getting run time error

### ISSUE THREAD

**Issue by jrohit54** [loadimpact/postman-to-k6#5]
rohit@bmdvrohitjai:~/Downloads/k6-v0.17.1-linux32$ ./k6 run Demo_script.js 

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.17.1!

  execution: local
     output: -
     script: /home/rohit/Downloads/k6-v0.17.1-linux32/Demo_script.js (js)

   duration: 0s, iterations: 1
        vus: 1, max: 1

    web ui: http://127.0.0.1:6565/

panic: runtime error: invalid memory address or nil pointer dereference-- / --
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80492cc]

goroutine 7 [running]:
sync/atomic.AddUint64(0x1a472414, 0x12e, 0x0, 0x1000, 0x12e)
	/usr/local/Cellar/go/1.8.3/libexec/src/sync/atomic/asm_386.s:112 +0xc
github.com/loadimpact/k6/lib/netext.(*Conn).Write(0x1a52d870, 0x1a081000, 0x12e, 0x1000, 0x12, 0x857b380, 0x197261c0)
	/Users/uppfinnarn/Projects/Go/src/github.com/loadimpact/k6/lib/netext/dialer.go:81 +0x70
net/http.persistConnWriter.Write(0x1a1fc0a0, 0x1a081000, 0x12e, 0x1000, 0xd0, 0x86166be, 0x3)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1133 +0x3f
bufio.(*Writer).Flush(0x19b92360, 0x88c4dc0, 0x19b92360)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:566 +0x5d
net/http.(*persistConn).writeLoop(0x1a1fc0a0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1709 +0x334
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1118 +0x8ac
rohit@bmdvrohitjai:~/Downloads/k6-v0.17.1-linux32$

**Comment by ppcano** [comment]
@jrohit54 The error looks to be `k6` command problem. 

Please, could you share your postman collection and/or the converted k6 script?

**Comment by jrohit54** [comment]
sure, i have attached the postman collection and converted k6 script also

[Files.zip](https://github.com/loadimpact/postman-to-k6/files/1230655/Files.zip)

**Comment by ppcano** [comment]
@jrohit54 The `postman-to-k6` converter is working well. 

The problem could be the `k6` installation, `k6` is not working. 

You could try another load script as the one in the [Getting started](https://docs.k6.io/docs/running-k6)

```
import http from "k6/http";

export default function() {
  http.get("http://test.loadimpact.com");
};)
```

I am not sure about your environment. Could it be that you are running the Linux `k6` binaries on a Mac?

I am closing this issue. Please, ask for Help in the [Slack channel](https://k6.io/slack/) or open an issue in the [k6 project](https://github.com/loadimpact/k6).

**Comment by jrohit54** [comment]
Yes , i was facing issue in particular version of k6 on linux OS.
v0.17.1- Facing above issue
v0.17.0  -Issue resolved

Thanks for you support.

**Comment by ppcano** [comment]
@jrohit54 If you know how to reproduce the error, it may help others if you create an issue in the [k6 project](https://github.com/loadimpact/k6/issues). 

Thanks!
