### ISSUE TITLE
Add option to log out response to command line

### ISSUE THREAD

**Issue by YOU54F** [loadimpact/postman-to-k6#50]
Adding the ability to output the response when running a test, would be really valuable for debugging purposes

```
 post(response) {
   console.log(JSON.stringify(response))
}
```

and the following will allow the output of the response body, which is useful if the output contains useful information

```
 post(response) {
   console.log(JSON.stringify(response.body))
}
```

It would be nice if we could pass a command line option when running `postman-to-k6` in order to do this, rather than having to add it in manually after the script is generated.

Not sure if this is preferable or useful to others, but thought I would raise it (happy for it to be closed!)

**Comment by simskij** [comment]
Thank you for the report! 🙏🏼

I agree with you that this would be nifty to have. I'll add it to the feature request list for further prioritizing. If you'd rather like to have a stab at implementing it yourself, I'd be happy to assist you in reviewing it and work towards having it merged.

**Comment by simskij** [comment]
After some more investigation, this is actually already possible using [`--http-debug`](https://k6.io/docs/using-k6/options#http-debug).
