### ISSUE TITLE
Published Docker image is out of date

### ISSUE THREAD

**Issue by Electrogenic** [loadimpact/postman-to-k6#59]
I'm wondering if it would be possible to push an updated docker image to hub.docker? The latest image I am able to find was last updated a year ago. https://hub.docker.com/r/loadimpact/postman-to-k6 

Thank you!

**Comment by simskij** [comment]
Thank you for the report!

This has now been automated, as of `v1.0.0`, so that every tag pushed to master following the `vX.X.X` pattern will result in a new version on both npm and dockerhub.
