### ISSUE TITLE
Could k6 check be added into the generated script?

### ISSUE THREAD

**Issue by liangway** [loadimpact/postman-to-k6#61]
Thanks a lot for implementing this tool, it's very easy to have k6 test script from postman.
And I have a noob question. 

Could we add [k6 checks](https://k6.io/docs/using-k6/checks) to the generated script? And how?

**Comment by simskij** [comment]
Hi!

Sure, just edit the output file adding the check you want! While this is indeed possible, we do recommend most users to rewrite the parts of their output that they want to modify using more k6 idiomatic code, as shown in the docs you refer to. In that case, you would have to replace the postman[Request] part to instead use the [HTTP client](https://k6.io/docs/using-k6/http-requests) directly.

For instance, given that you have a request that looks like this in your output:

```js
    postman[Request]({
      name: "Get page",
      id: "4c08d3d5-93d8-4c78-a6d2-212e3fcf2404",
      method: "GET",
      address: "https://test-api.k6.io/",
      data: {},
    });
```

you may add the `post` property to that object to do assertions post the request being executed:

```diff

    postman[Request]({
      name: "Get page",
      id: "4c08d3d5-93d8-4c78-a6d2-212e3fcf2404",
      method: "GET",
      address: "https://test-api.k6.io/",
      post(response) {
+       tests["Status code is 200"] = responseCode.code === 200;
      }
    });
```

Hope that helps,
Simme
