### ISSUE TITLE
Convert collection that uses Environment Variables

### ISSUE THREAD

**Issue by pjamgithub** [loadimpact/postman-to-k6#7]
I have postman collections I wish to load test, but my collections are run with the -e option to designate the environment variables it needs.  Can this convert collections that also use environment variables and if so, what is the command for that?

**Comment by ppcano** [comment]
Your variables will be defined at the top of the generated `k6` script as:


```
import { group } from "k6";
import http from "k6/http";

let url = "YOUR_VALUE";
let username = "YOUR_VALUE";
let repository = "YOUR_VALUE";
let branch = "YOUR_VALUE";
let token = "YOUR_VALUE";


export let options = {
  maxRedirects: 4
}

export default function() {

  group("Repositories", function() {

    let res;
    
    /**
    postman.setEnvironmentVariable("username", "a85");
    postman.setEnvironmentVariable("repository", "Newman")
    **/
    res = http.get("http://"+url+"/repos/"+username+"/"+repository+"/contributors");


```
You could check out the output with one of the repo examples:
`bin/postman-to-k6.js examples/postman/v2/github.json -o k6-script.js`

After the k6 file is generated, you have to edit the k6 script to assign the variable values. 

```

let url = "http://loadimpact.com";
let username = "ppcano";
...
```

As well, you could also use [environment variables with k6](https://k6.readme.io/docs/environment-variables):
```

let url = __ENV.MY_URL;
let username = __ENV.MY_USERNAME;
...
```

**Comment by pjamgithub** [comment]
Thank you! That works

**Comment by robingustafsson** [comment]
@pjamgithub We released a new version of the converter today that has broader support for the Postman feature set, including support for environment variables. If you export your environment variables from Postman (to say `MyEnvVars.postman_environment.json`) you can now convert a collection like this:

```shel
postman-to-k6 MyCollection.postman_collection.json -o MyTest.js -e MyEnvVars.postman_environment.json
```
