### ISSUE TITLE
Not able to run the test

### ISSUE THREAD

**Issue by YeswanthNag5** [loadimpact/postman-to-k6#9]
I am able to convert my postman collection to k6 format by load impact converter.
But, how can i generate Load ?

Is my understanding right that this tool will help in load testing as we have a user SLA ?

**Comment by ppcano** [comment]
@YeswanthNag5 

If you have created your `k6 script`, you can run it with `k6`.

`k6 run your-script.js`


`k6 run --vus 10 --duration 30s your-script.js`



Check out the [k6 docs](https://k6.readme.io/docs/welcome) to know the different [k6 options](https://k6.readme.io/docs/options#section-available-options) and [features](https://k6.readme.io/docs/welcome#section-features).



Happy load testing!

**Comment by YeswanthNag5** [comment]
When trying to execute, it complains that k6 is not a command. 

I tried executing from bin folder.

**Comment by ppcano** [comment]
@YeswanthNag5 

Likely, `k6` is not installed in your PATH.

https://docs.k6.io/docs/installation

You could join the Slack group for k6 support questions:

https://k6.io/slack/
